export const manyangAssets = {
  backgrounds: {
    default: "/manyang/backgrounds/default.webp",
    blackCatHome: "/manyang/backgrounds/home-black-cat.webp",
    whiteCatHome: "/manyang/backgrounds/home-white-cat-ref.webp",
    cheeseCatHome: "/manyang/backgrounds/home-cheese-cat.webp",
    grayCatHome: "/manyang/backgrounds/home-gray-cat.webp",
    blackCatInterpretation: "/manyang/backgrounds/interpretation-black-cat.webp",
    whiteCatInterpretation: "/manyang/backgrounds/interpretation-white-cat.webp",
    cheeseCatInterpretation: "/manyang/backgrounds/interpretation-cheese-cat.webp",
    grayCatInterpretation: "/manyang/backgrounds/interpretation-gray-cat.webp",
    themeFrames: {
      blackCat: "/manyang/backgrounds/theme-background-black-cat-v4.png",
      whiteCat: "/manyang/backgrounds/theme-background-white-cat-v4.png",
      cheeseCat: "/manyang/backgrounds/theme-background-cheese-cat-v4.png",
      grayCat: "/manyang/backgrounds/theme-background-gray-cat-v4.png",
    },
  },
  illustrations: {
    dreamseedByCat: {
      blackCat: "/manyang/backgrounds/dreamseed-background-black-cat-v2.webp",
      whiteCat: "/manyang/backgrounds/dreamseed-background-white-cat-v2.webp",
      cheeseCat: "/manyang/backgrounds/dreamseed-background-cheese-cat-v3.webp",
      grayCat: "/manyang/backgrounds/dreamseed-background-gray-cat-v2.webp",
    },
    encyclopediaBanners: {
      blackCat: "/manyang/encyclopedia/encyclopedia-banner-black-cat-v3.webp",
      whiteCat: "/manyang/encyclopedia/encyclopedia-banner-white-cat-v3.webp",
      cheeseCat: "/manyang/encyclopedia/encyclopedia-banner-cheese-cat-v3.webp",
      grayCat: "/manyang/encyclopedia/encyclopedia-banner-gray-cat-v3.webp",
    },
    morning: "/manyang/backgrounds/morning-illustration.webp",
    blackCatProfile: "/manyang/references/cat-black-profile.webp",
    whiteCatProfile: "/manyang/references/cat-white-profile.webp",
    cheeseCatProfile: "/manyang/references/cat-cheese-profile.webp",
    grayCatProfile: "/manyang/references/cat-gray-profile.webp",
    blackCat: "/manyang/references/cat-black-profile.webp",
    whiteCat: "/manyang/references/cat-white-profile.webp",
    cheeseCat: "/manyang/references/cat-cheese-profile.webp",
    grayCat: "/manyang/references/cat-gray-profile.webp",
  },
  loadingReaders: {
    blackCat: "/manyang/references/loading-black-cat.webp",
    whiteCat: "/manyang/references/loading-white-cat.webp",
    cheeseCat: "/manyang/references/loading-cheese-cat.webp",
    grayCat: "/manyang/references/loading-gray-cat.webp",
  },
  social: {
    sharePreview: "/manyang/social/og-blackcat.jpg",
  },
  orbs: {
    base: "/manyang/orbs/orb-transparent.webp",
    one: "/manyang/orbs/orb-1-transparent.webp",
    two: "/manyang/orbs/orb-2-transparent.webp",
    three: "/manyang/orbs/orb-3-transparent.webp",
  },
  receiptStamps: {
    blackCat: "/manyang/receipts/stamps/stamp-black-cat-seal.png",
    whiteCat: "/manyang/receipts/stamps/stamp-white-cat-seal.png",
    cheeseCat: "/manyang/receipts/stamps/stamp-cheese-cat-seal.png",
    grayCat: "/manyang/receipts/stamps/stamp-gray-cat-seal.png",
  },
  tarot: {
    cardBack: "/manyang/tarot/card-back.png",
    major: {
      fool: "/manyang/tarot/major/00-the-fool.png",
      magician: "/manyang/tarot/major/01-the-magician.png",
      highPriestess: "/manyang/tarot/major/02-the-high-priestess.png",
      empress: "/manyang/tarot/major/03-the-empress.png",
      emperor: "/manyang/tarot/major/04-the-emperor.png",
      hierophant: "/manyang/tarot/major/05-the-hierophant.png",
      lovers: "/manyang/tarot/major/06-the-lovers.png",
      chariot: "/manyang/tarot/major/07-the-chariot.png",
      strength: "/manyang/tarot/major/08-strength.png",
      hermit: "/manyang/tarot/major/09-the-hermit.png",
      wheelOfFortune: "/manyang/tarot/major/10-wheel-of-fortune.png",
      justice: "/manyang/tarot/major/11-justice.png",
      hangedMan: "/manyang/tarot/major/12-the-hanged-man.png",
      death: "/manyang/tarot/major/13-death.png",
      temperance: "/manyang/tarot/major/14-temperance.png",
      devil: "/manyang/tarot/major/15-the-devil.png",
      tower: "/manyang/tarot/major/16-the-tower.png",
      star: "/manyang/tarot/major/17-the-star.png",
      moon: "/manyang/tarot/major/18-the-moon.png",
      sun: "/manyang/tarot/major/19-the-sun.png",
      judgement: "/manyang/tarot/major/20-judgement.png",
      world: "/manyang/tarot/major/21-the-world.png",
    },
  },
  buttons: {
    dreammemoryWrite: "/manyang/ui/buttons/dreammemory-write-frame-slim.png",
    dreammemoryForgot: "/manyang/ui/buttons/dreammemory-forgot-frame.png",
    dreammemorySubmit: "/manyang/ui/buttons/dreammemory-submit-frame-slim.png",
    dreamseed: "/manyang/ui/buttons/dreamseed-frame.png",
    dreamseedArchive: "/manyang/ui/buttons/dreamseed-archive-frame.png",
    morningPawprint: "/manyang/ui/buttons/morning-pawprint-frame.png",
    compactPrimary: "/manyang/ui/buttons/common-compact-primary-frame.png",
    mediumPrimary: "/manyang/ui/buttons/common-medium-primary-frame.png",
    mediumSecondary: "/manyang/ui/buttons/common-medium-secondary-frame.png",
  },
  footer: {
    frame: "/manyang/ui/footer/footer-frame.png",
    icons: {
      today: "/manyang/ui/footer/footer-icon-today.png",
      write: "/manyang/ui/footer/footer-icon-write.png",
      archive: "/manyang/ui/footer/footer-icon-archive.png",
      encyclopedia: "/manyang/ui/footer/footer-icon-encyclopedia.png",
      profile: "/manyang/ui/footer/footer-icon-profile.png",
    },
  },
  basicIcons: {
    moon: "/manyang/ui/basic-icons/basic-moon.png",
    paw: "/manyang/ui/basic-icons/basic-paw.png",
    sparkles: "/manyang/ui/basic-icons/basic-sparkles.png",
    crystalBall: "/manyang/ui/basic-icons/basic-crystal-ball.png",
    pencil: "/manyang/ui/basic-icons/basic-pencil.png",
    book: "/manyang/ui/basic-icons/basic-book.png",
    settings: "/manyang/ui/basic-icons/basic-settings.png",
    profile: "/manyang/ui/basic-icons/basic-profile.png",
  },
  actionIcons: {
    arrowLeft: "/manyang/ui/action-icons/action-arrow-left.png",
    arrowRight: "/manyang/ui/action-icons/action-arrow-right.png",
    share: "/manyang/ui/action-icons/action-share.png",
    bell: "/manyang/ui/action-icons/action-bell.png",
    settings: "/manyang/ui/action-icons/action-settings.png",
    trash: "/manyang/ui/action-icons/action-trash.png",
    profile: "/manyang/ui/action-icons/action-profile.png",
    calendar: "/manyang/ui/action-icons/action-calendar.png",
    pencil: "/manyang/ui/action-icons/action-pencil.png",
    book: "/manyang/ui/action-icons/action-book.png",
    search: "/manyang/ui/action-icons/action-search.png",
    download: "/manyang/ui/action-icons/action-download.png",
    more: "/manyang/ui/action-icons/action-more.png",
    close: "/manyang/ui/action-icons/action-close.png",
    check: "/manyang/ui/action-icons/action-check.png",
    help: "/manyang/ui/action-icons/action-help.png",
  },
  pageIcons: {
    today: "/manyang/ui/page-icons/page-today.png",
    write: "/manyang/ui/page-icons/page-write.png",
    archive: "/manyang/ui/page-icons/page-archive.png",
    encyclopedia: "/manyang/ui/page-icons/page-encyclopedia.png",
    profile: "/manyang/ui/page-icons/page-profile.png",
    dreamReceipt: "/manyang/ui/page-icons/page-dream-receipt.png",
    morningPawprint: "/manyang/ui/page-icons/page-morning-pawprint.png",
    nightRecord: "/manyang/ui/page-icons/page-night-record.png",
    tarot: "/manyang/ui/page-icons/page-tarot.png",
  },
  semanticIcons: {
    moon: "/manyang/ui/semantic-icons/semantic-moon.png",
    paw: "/manyang/ui/semantic-icons/semantic-paw.png",
    sparkles: "/manyang/ui/semantic-icons/semantic-sparkles.png",
    cloud: "/manyang/ui/semantic-icons/semantic-cloud.png",
    feather: "/manyang/ui/semantic-icons/semantic-feather.png",
    lantern: "/manyang/ui/semantic-icons/semantic-lantern.png",
    potion: "/manyang/ui/semantic-icons/semantic-potion.png",
    key: "/manyang/ui/semantic-icons/semantic-key.png",
    door: "/manyang/ui/semantic-icons/semantic-door.png",
    crystalBall: "/manyang/ui/semantic-icons/semantic-crystal-ball.png",
    crystals: "/manyang/ui/semantic-icons/semantic-crystals.png",
    star: "/manyang/ui/semantic-icons/semantic-star.png",
  },
  calendarRecordIcons: {
    dream: "/manyang/ui/calendar-record-icons/calendar-record-dream.png",
    pawprint: "/manyang/ui/calendar-record-icons/calendar-record-pawprint.png",
    night: "/manyang/ui/calendar-record-icons/calendar-record-night.png",
    symbol: "/manyang/ui/calendar-record-icons/calendar-record-symbol.png",
  },
  encyclopediaIcons: {
    place: "/manyang/ui/encyclopedia-icons/encyclopedia-place.png",
    person: "/manyang/ui/encyclopedia-icons/encyclopedia-person.png",
    animal: "/manyang/ui/encyclopedia-icons/encyclopedia-animal.png",
    nature: "/manyang/ui/encyclopedia-icons/encyclopedia-nature.png",
    object: "/manyang/ui/encyclopedia-icons/encyclopedia-object.png",
    body: "/manyang/ui/encyclopedia-icons/encyclopedia-body.png",
    action: "/manyang/ui/encyclopedia-icons/encyclopedia-action.png",
    event: "/manyang/ui/encyclopedia-icons/encyclopedia-event.png",
    food: "/manyang/ui/encyclopedia-icons/encyclopedia-food.png",
    emotion: "/manyang/ui/encyclopedia-icons/encyclopedia-emotion.png",
    abstract: "/manyang/ui/encyclopedia-icons/encyclopedia-abstract.png",
  },
  keywordIcons: {
    peaceful: "/manyang/ui/keyword-icons/keyword-peaceful.png",
    warm: "/manyang/ui/keyword-icons/keyword-warm.png",
    excited: "/manyang/ui/keyword-icons/keyword-excited.png",
    wistful: "/manyang/ui/keyword-icons/keyword-wistful.png",
    sad: "/manyang/ui/keyword-icons/keyword-sad.png",
    lonely: "/manyang/ui/keyword-icons/keyword-lonely.png",
    anxious: "/manyang/ui/keyword-icons/keyword-anxious.png",
    fearful: "/manyang/ui/keyword-icons/keyword-fearful.png",
    stifling: "/manyang/ui/keyword-icons/keyword-stifling.png",
    unfamiliar: "/manyang/ui/keyword-icons/keyword-unfamiliar.png",
    eerie: "/manyang/ui/keyword-icons/keyword-eerie.png",
    mystical: "/manyang/ui/keyword-icons/keyword-mystical.png",
    hazy: "/manyang/ui/keyword-icons/keyword-hazy.png",
    complex: "/manyang/ui/keyword-icons/keyword-complex.png",
    unpleasant: "/manyang/ui/keyword-icons/keyword-unpleasant.png",
    vivid: "/manyang/ui/keyword-icons/keyword-vivid.png",
    heavy: "/manyang/ui/keyword-icons/keyword-heavy.png",
    stuck: "/manyang/ui/keyword-icons/keyword-stuck.png",
    falling: "/manyang/ui/keyword-icons/keyword-falling.png",
    floating: "/manyang/ui/keyword-icons/keyword-floating.png",
    chased: "/manyang/ui/keyword-icons/keyword-chased.png",
    cold: "/manyang/ui/keyword-icons/keyword-cold.png",
    composed: "/manyang/ui/keyword-icons/keyword-composed.png",
    curious: "/manyang/ui/keyword-icons/keyword-curious.png",
    relieved: "/manyang/ui/keyword-icons/keyword-relieved.png",
    scared: "/manyang/ui/keyword-icons/keyword-scared.png",
    irritated: "/manyang/ui/keyword-icons/keyword-irritated.png",
    uneasy: "/manyang/ui/keyword-icons/keyword-uneasy.png",
    empty: "/manyang/ui/keyword-icons/keyword-empty.png",
    dazed: "/manyang/ui/keyword-icons/keyword-dazed.png",
    refreshed: "/manyang/ui/keyword-icons/keyword-refreshed.png",
    lightEasy: "/manyang/ui/keyword-icons/keyword-light-easy.png",
    relaxed: "/manyang/ui/keyword-icons/keyword-relaxed.png",
    drowsy: "/manyang/ui/keyword-icons/keyword-drowsy.png",
    tired: "/manyang/ui/keyword-icons/keyword-tired.png",
    tense: "/manyang/ui/keyword-icons/keyword-tense.png",
    racing: "/manyang/ui/keyword-icons/keyword-racing.png",
    stiff: "/manyang/ui/keyword-icons/keyword-stiff.png",
    coldSweat: "/manyang/ui/keyword-icons/keyword-cold-sweat.png",
    wornOut: "/manyang/ui/keyword-icons/keyword-worn-out.png",
    low: "/manyang/ui/keyword-icons/keyword-low.png",
    lightBody: "/manyang/ui/keyword-icons/keyword-light-body.png",
    sensitive: "/manyang/ui/keyword-icons/keyword-sensitive.png",
    okay: "/manyang/ui/keyword-icons/keyword-okay.png",
  },
  sectionIcons: {
    dreamInput: "/manyang/ui/section-icons/section-dream-input.png",
    dreamAtmosphere: "/manyang/ui/section-icons/section-dream-atmosphere.png",
    dreamSensation: "/manyang/ui/section-icons/section-dream-sensation.png",
    morning: "/manyang/ui/section-icons/section-morning.png",
    morningMood: "/manyang/ui/section-icons/section-morning-mood.png",
    bodyCondition: "/manyang/ui/section-icons/section-body-condition.png",
    nightMood: "/manyang/ui/section-icons/section-night-mood.png",
    nightCondition: "/manyang/ui/section-icons/section-night-condition.png",
    oneLineNote: "/manyang/ui/section-icons/section-one-line-note.png",
  },
  profileIcons: {
    notifications: "/manyang/ui/profile-icons/profile-notifications.png",
    privacy: "/manyang/ui/profile-icons/profile-privacy.png",
    theme: "/manyang/ui/profile-icons/profile-theme.png",
    moonPass: "/manyang/ui/profile-icons/profile-moon-pass.png",
    service: "/manyang/ui/profile-icons/profile-service.png",
    account: "/manyang/ui/profile-icons/profile-account.png",
  },
  profileMenuIcons: {
    recordBackup: "/manyang/ui/profile-menu-icons/profile-menu-record-backup.png",
    recordExport: "/manyang/ui/profile-menu-icons/profile-menu-record-export.png",
    recordDelete: "/manyang/ui/profile-menu-icons/profile-menu-record-delete.png",
    feedback: "/manyang/ui/profile-menu-icons/profile-menu-feedback.png",
    terms: "/manyang/ui/profile-menu-icons/profile-menu-terms.png",
    privacySecurity: "/manyang/ui/profile-menu-icons/profile-menu-privacy-security.png",
    privacyPolicy: "/manyang/ui/profile-menu-icons/profile-menu-privacy-policy.png",
    appVersion: "/manyang/ui/profile-menu-icons/profile-menu-app-version.png",
    morningPawprint: "/manyang/ui/profile-menu-icons/profile-menu-morning-pawprint.png",
  },
} as const;

export type KeywordIconName = keyof typeof manyangAssets.keywordIcons;
export type SectionIconName = keyof typeof manyangAssets.sectionIcons;
export type CalendarRecordIconName = keyof typeof manyangAssets.calendarRecordIcons;
