import { manyangAssets } from "./manyang-assets";

export type TarotMajorCard = {
  id: number;
  roman: string;
  slug: string;
  nameEn: string;
  nameKo: string;
  image: string;
  keywords: readonly string[];
  visualSymbols: readonly string[];
  mood: string;
  upright: { summary: string; dailyFlow: string; advice: string };
  reversed: { summary: string; dailyFlow: string; advice: string };
  contexts: { love: string; career: string; money: string; general: string };
};

export const tarotMajorCards = [
  {
    id: 0,
    roman: "0",
    slug: "the-fool",
    nameEn: "THE FOOL",
    nameKo: "바보",
    image: manyangAssets.tarot.major.fool,
    keywords: ["시작", "가능성", "모험", "순수함"],
    visualSymbols: ["절벽 끝의 여행자", "작은 보따리", "흰 꽃", "작은 개"],
    mood: "밝고 가벼운 출발감 속에 아직 정해지지 않은 길이 열려 있는 분위기입니다.",
    upright: {
      summary: "새로운 시작과 열린 가능성이 자연스럽게 떠오르는 흐름을 보여 줍니다.",
      dailyFlow: "낯선 제안이나 작은 시도가 하루의 방향을 바꿀 수 있는 날로 읽을 수 있습니다.",
      advice: "첫걸음을 내딛되 발밑의 조건과 기본 준비를 함께 확인하세요.",
    },
    reversed: {
      summary: "설렘이 앞서 준비나 책임감이 느슨해질 수 있는 흐름을 비춥니다.",
      dailyFlow: "즉흥적인 선택이 잦아질 수 있으니 속도를 한 번 낮추는 편이 좋습니다.",
      advice: "호기심은 살리되 안전장치와 현실적인 기준을 먼저 세워 보세요.",
    },
    contexts: {
      love: "새로운 호감이나 아직 정의되지 않은 관계의 가능성을 상징합니다.",
      career: "새 프로젝트나 진로 탐색처럼 경험보다 가능성이 앞서는 장면에 가깝습니다.",
      money: "새 수익 실험은 열려 있지만 충동 지출은 살펴볼 필요가 있습니다.",
      general: "결론보다 시작의 마음과 선택 가능한 길을 살피는 카드입니다.",
    },
  },
  {
    id: 1,
    roman: "I",
    slug: "the-magician",
    nameEn: "THE MAGICIAN",
    nameKo: "마법사",
    image: manyangAssets.tarot.major.magician,
    keywords: ["실행", "창조", "의지", "구현"],
    visualSymbols: ["위와 아래를 잇는 손짓", "무한대 기호", "네 가지 도구", "제단"],
    mood: "생각을 현실의 형태로 옮기려는 집중되고 능동적인 창조 에너지입니다.",
    upright: {
      summary: "이미 가진 자원과 역량을 조합해 결과를 만들어 갈 수 있는 흐름입니다.",
      dailyFlow: "말이나 아이디어에 그치지 않고 작은 실행으로 옮길 때 힘이 생깁니다.",
      advice: "필요한 도구를 다시 확인하고 지금 가능한 행동 하나를 시작하세요.",
    },
    reversed: {
      summary: "능력은 있으나 방향이 흩어지거나 말과 행동이 어긋날 수 있습니다.",
      dailyFlow: "계획을 크게 말하기보다 실제로 쓸 수 있는 시간과 자원을 점검해야 합니다.",
      advice: "과장이나 조급함을 줄이고 한 가지 목표에 집중해 보세요.",
    },
    contexts: {
      love: "매력과 표현력이 강해지는 흐름이며 진솔한 소통이 중요합니다.",
      career: "기술과 기획을 실제 성과로 연결할 기회가 보일 수 있습니다.",
      money: "가진 역량을 수익 구조로 바꾸는 실험에 적합한 흐름입니다.",
      general: "영감이 현실화되려면 의식적인 실행이 필요하다는 신호입니다.",
    },
  },
  {
    id: 2,
    roman: "II",
    slug: "the-high-priestess",
    nameEn: "THE HIGH PRIESTESS",
    nameKo: "여사제",
    image: manyangAssets.tarot.major.highPriestess,
    keywords: ["직감", "비밀", "무의식", "침묵"],
    visualSymbols: ["두 기둥", "베일", "책", "달의 상징"],
    mood: "겉으로 드러난 정보보다 조용한 감각과 숨은 흐름이 중요한 분위기입니다.",
    upright: {
      summary: "아직 모든 것이 공개되지 않았고 관찰과 직감이 길잡이가 되는 흐름입니다.",
      dailyFlow: "서두른 결론보다 분위기와 반복되는 신호를 살피는 시간이 어울립니다.",
      advice: "말을 늘리기보다 정보를 모으고 내면의 감각을 차분히 확인하세요.",
    },
    reversed: {
      summary: "직감을 무시하거나 감춰진 사실을 외면하면서 혼란이 커질 수 있습니다.",
      dailyFlow: "확인되지 않은 추측이 커질 수 있으니 침묵과 회피를 구분해야 합니다.",
      advice: "불안을 사실로 단정하지 말고 필요한 질문을 조심스럽게 정리하세요.",
    },
    contexts: {
      love: "말하지 않은 감정이나 아직 분명하지 않은 관계의 속마음을 뜻할 수 있습니다.",
      career: "내부 사정이나 자료 검토처럼 보이지 않는 정보 수집이 중요합니다.",
      money: "조건을 다 알기 전에는 큰 결정을 미루고 세부 항목을 살피는 편이 좋습니다.",
      general: "겉으로 보이는 사건 아래의 패턴과 감각을 읽어야 하는 카드입니다.",
    },
  },
  {
    id: 3,
    roman: "III",
    slug: "the-empress",
    nameEn: "THE EMPRESS",
    nameKo: "여황제",
    image: manyangAssets.tarot.major.empress,
    keywords: ["풍요", "생명력", "돌봄", "창조성"],
    visualSymbols: ["풍성한 정원", "곡식", "왕관", "비너스 상징"],
    mood: "무언가가 자연스럽게 자라고 감각적으로 풍성해지는 따뜻한 분위기입니다.",
    upright: {
      summary: "성장과 돌봄, 창작의 에너지가 부드럽게 확장되는 흐름입니다.",
      dailyFlow: "억지로 밀어붙이기보다 잘 자랄 환경을 마련할 때 결과가 부드럽습니다.",
      advice: "통제보다 돌봄을 선택하고 몸과 감각이 보내는 신호도 존중하세요.",
    },
    reversed: {
      summary: "과잉 보호나 의존, 감정적 소비가 성장의 균형을 흐릴 수 있습니다.",
      dailyFlow: "무리하게 챙기거나 퍼주면서 정작 자신의 리듬을 놓치기 쉽습니다.",
      advice: "돌봄과 경계 사이의 균형을 다시 세우고 필요한 만큼만 나누세요.",
    },
    contexts: {
      love: "애정과 친밀감이 자라는 흐름이며 편안한 표현이 도움이 됩니다.",
      career: "창작, 브랜드, 콘텐츠처럼 키워 가는 일이 두드러질 수 있습니다.",
      money: "풍요의 가능성은 있으나 즐거움에 따른 과소비를 살펴야 합니다.",
      general: "서두른 결론보다 성장의 환경을 가꾸는 태도가 어울립니다.",
    },
  },
  {
    id: 4,
    roman: "IV",
    slug: "the-emperor",
    nameEn: "THE EMPEROR",
    nameKo: "황제",
    image: manyangAssets.tarot.major.emperor,
    keywords: ["질서", "구조", "권위", "책임"],
    visualSymbols: ["왕좌", "갑옷", "산", "양의 상징"],
    mood: "단단한 기준과 현실적인 통제력이 중심을 잡는 안정적인 분위기입니다.",
    upright: {
      summary: "흩어진 상황에 구조와 책임을 세워 안정시키는 흐름입니다.",
      dailyFlow: "감정적인 반응보다 규칙, 일정, 역할 정리가 유리하게 작용합니다.",
      advice: "기준을 분명히 하고 지켜야 할 책임을 구체적인 행동으로 옮기세요.",
    },
    reversed: {
      summary: "통제가 지나치거나 반대로 책임을 피하며 질서가 흔들릴 수 있습니다.",
      dailyFlow: "고집이나 경직된 태도가 대화를 막을 수 있어 유연함이 필요합니다.",
      advice: "권위를 증명하려 하기보다 필요한 구조가 무엇인지 다시 보세요.",
    },
    contexts: {
      love: "안정과 책임을 원하지만 통제적인 방식은 조심해야 합니다.",
      career: "관리, 리더십, 시스템 정비가 중요한 흐름으로 읽을 수 있습니다.",
      money: "예산과 원칙을 세워 현실적으로 관리할 필요가 있습니다.",
      general: "감정보다 기준과 구조를 통해 상황을 다루라는 카드입니다.",
    },
  },
  {
    id: 5,
    roman: "V",
    slug: "the-hierophant",
    nameEn: "THE HIEROPHANT",
    nameKo: "교황",
    image: manyangAssets.tarot.major.hierophant,
    keywords: ["전통", "배움", "제도", "신념"],
    visualSymbols: ["사제", "두 제자", "열쇠", "기둥"],
    mood: "개인의 즉흥보다 검증된 지식과 공동체의 규칙이 힘을 갖는 분위기입니다.",
    upright: {
      summary: "배움, 멘토, 제도권의 조언을 통해 방향을 잡기 좋은 흐름입니다.",
      dailyFlow: "혼자 해석하기보다 경험 많은 사람이나 공식 절차를 참고하면 안정적입니다.",
      advice: "검증된 길을 살피고 지금 필요한 가르침을 받아들여 보세요.",
    },
    reversed: {
      summary: "낡은 규칙이나 형식주의가 현재 상황에 맞지 않을 수 있습니다.",
      dailyFlow: "규칙을 따르는 것과 스스로의 신념을 확인하는 것 사이에서 고민이 생깁니다.",
      advice: "관습을 무조건 거부하거나 따르기보다 지금의 의미를 점검하세요.",
    },
    contexts: {
      love: "공식적인 약속이나 관계의 가치관을 확인하는 흐름입니다.",
      career: "교육, 자격, 멘토링, 조직 절차가 중요한 단서가 될 수 있습니다.",
      money: "전문가 조언과 검증된 방식이 안정감을 줄 수 있습니다.",
      general: "혼자만의 판단보다 전통과 배움의 틀을 활용하라는 카드입니다.",
    },
  },
  {
    id: 6,
    roman: "VI",
    slug: "the-lovers",
    nameEn: "THE LOVERS",
    nameKo: "연인",
    image: manyangAssets.tarot.major.lovers,
    keywords: ["사랑", "선택", "결합", "가치관"],
    visualSymbols: ["두 인물", "천사", "나무", "빛의 축복"],
    mood: "마음의 끌림과 가치의 선택이 함께 드러나는 연결의 분위기입니다.",
    upright: {
      summary: "관계나 선택에서 진심과 가치관의 일치가 중요해지는 흐름입니다.",
      dailyFlow: "무엇을 고를지보다 무엇과 연결되고 싶은지 묻는 장면이 생길 수 있습니다.",
      advice: "끌림만 보지 말고 선택이 지지하는 가치와 책임을 함께 확인하세요.",
    },
    reversed: {
      summary: "마음과 선택이 어긋나거나 관계 안의 불균형이 느껴질 수 있습니다.",
      dailyFlow: "결정을 미루거나 상대에게 맞추기만 하면 피로가 쌓일 수 있습니다.",
      advice: "관계의 조화보다 먼저 자신의 기준과 진심을 선명하게 정리하세요.",
    },
    contexts: {
      love: "강한 끌림과 관계의 선택이 함께 놓인 흐름입니다.",
      career: "협업이나 파트너십에서 가치관의 일치가 중요합니다.",
      money: "공동 결정이나 계약에서 서로의 기준을 분명히 해야 합니다.",
      general: "선택의 표면보다 그 선택이 연결하는 가치를 보라는 카드입니다.",
    },
  },
  {
    id: 7,
    roman: "VII",
    slug: "the-chariot",
    nameEn: "THE CHARIOT",
    nameKo: "전차",
    image: manyangAssets.tarot.major.chariot,
    keywords: ["전진", "승리", "의지", "방향성"],
    visualSymbols: ["전차", "흑백 스핑크스", "갑옷", "도시의 문"],
    mood: "상반된 힘을 한 방향으로 묶어 앞으로 나아가려는 긴장감 있는 분위기입니다.",
    upright: {
      summary: "목표를 정하고 집중하면 상황을 추진할 수 있는 흐름입니다.",
      dailyFlow: "여러 요구가 동시에 와도 우선순위를 잡으면 움직임이 빨라집니다.",
      advice: "방향을 분명히 하고 감정과 행동을 같은 목표에 맞춰 보세요.",
    },
    reversed: {
      summary: "방향을 잃거나 지나친 힘으로 상황을 밀어붙일 수 있습니다.",
      dailyFlow: "서두르는 마음 때문에 세부 조율이 빠질 수 있어 속도 조절이 필요합니다.",
      advice: "목표와 동기를 다시 확인하고 불필요한 경쟁심은 내려놓으세요.",
    },
    contexts: {
      love: "관계를 바꾸거나 이끌고 싶은 의지가 강해질 수 있습니다.",
      career: "경쟁, 프로젝트 추진, 목표 달성의 흐름과 맞닿아 있습니다.",
      money: "공격적인 전략보다 방향과 리스크 관리가 중요합니다.",
      general: "흔들리는 힘을 모아 앞으로 나아가라는 카드입니다.",
    },
  },
  {
    id: 8,
    roman: "VIII",
    slug: "strength",
    nameEn: "STRENGTH",
    nameKo: "힘",
    image: manyangAssets.tarot.major.strength,
    keywords: ["내면의 힘", "용기", "인내", "부드러운 통제"],
    visualSymbols: ["사자", "여인", "무한대 기호", "꽃장식"],
    mood: "거친 힘을 누르기보다 부드럽게 다스리는 조용한 용기의 분위기입니다.",
    upright: {
      summary: "인내와 다정한 통제로 어려운 감정이나 상황을 다룰 수 있는 흐름입니다.",
      dailyFlow: "강한 반응보다 차분한 태도가 더 큰 영향력을 만들 수 있습니다.",
      advice: "상대를 이기려 하기보다 자신 안의 힘을 부드럽게 길들여 보세요.",
    },
    reversed: {
      summary: "자신감 부족이나 억눌린 감정이 갑작스럽게 드러날 수 있습니다.",
      dailyFlow: "참기만 하거나 반대로 폭발하지 않도록 감정의 출구를 마련해야 합니다.",
      advice: "약함을 탓하지 말고 회복 가능한 리듬과 지지 기반을 먼저 찾으세요.",
    },
    contexts: {
      love: "이해와 인내가 관계를 안정시키는 흐름입니다.",
      career: "압박 속에서도 꾸준히 버티는 힘이 필요합니다.",
      money: "충동을 조절하고 장기적인 습관을 다듬는 데 초점이 있습니다.",
      general: "진짜 힘은 강압보다 부드러운 자기 조절에서 나온다는 카드입니다.",
    },
  },
  {
    id: 9,
    roman: "IX",
    slug: "the-hermit",
    nameEn: "THE HERMIT",
    nameKo: "은둔자",
    image: manyangAssets.tarot.major.hermit,
    keywords: ["고독", "성찰", "지혜", "내면 탐색"],
    visualSymbols: ["등불", "지팡이", "망토", "눈 덮인 산"],
    mood: "소란에서 물러나 내면의 등불로 길을 비추는 고요한 분위기입니다.",
    upright: {
      summary: "혼자만의 성찰과 경험에서 우러난 지혜가 필요한 흐름입니다.",
      dailyFlow: "즉답보다 생각을 정리할 시간을 갖는 편이 더 정확한 판단을 돕습니다.",
      advice: "외부 소음에서 잠시 떨어져 지금의 질문을 깊게 들여다보세요.",
    },
    reversed: {
      summary: "고독이 성찰이 아니라 단절이나 회피로 굳어질 수 있습니다.",
      dailyFlow: "혼자 해결하려는 마음이 강해져 필요한 도움을 놓칠 수 있습니다.",
      advice: "침묵이 길어졌다면 믿을 만한 사람에게 한 가지 질문을 꺼내 보세요.",
    },
    contexts: {
      love: "거리 두기나 관계의 의미를 다시 묻는 시간이 필요할 수 있습니다.",
      career: "전문성, 연구, 독립적인 판단이 중요한 흐름입니다.",
      money: "조용히 자료를 검토하고 장기 기준을 세우는 데 어울립니다.",
      general: "답을 밖에서 찾기보다 내면의 등불을 따라가라는 카드입니다.",
    },
  },
  {
    id: 10,
    roman: "X",
    slug: "wheel-of-fortune",
    nameEn: "WHEEL OF FORTUNE",
    nameKo: "운명의 수레바퀴",
    image: manyangAssets.tarot.major.wheelOfFortune,
    keywords: ["변화", "순환", "전환점", "타이밍"],
    visualSymbols: ["회전하는 바퀴", "사방의 존재", "구름", "상징 문자"],
    mood: "고정되어 보이던 흐름이 움직이고 국면이 전환되는 역동적인 분위기입니다.",
    upright: {
      summary: "상황의 주기가 바뀌며 새로운 타이밍이 열릴 수 있는 흐름입니다.",
      dailyFlow: "예상 밖의 변화가 있어도 흐름에 맞춰 유연하게 움직이는 편이 좋습니다.",
      advice: "붙잡기보다 변화를 읽고 지금 올라탈 수 있는 리듬을 찾으세요.",
    },
    reversed: {
      summary: "변화를 거부하거나 타이밍이 어긋나며 같은 패턴이 반복될 수 있습니다.",
      dailyFlow: "계획과 실제 흐름이 달라질 수 있으니 여지를 남겨 두는 것이 좋습니다.",
      advice: "통제할 수 없는 부분은 인정하고 반복되는 선택 패턴을 점검하세요.",
    },
    contexts: {
      love: "관계의 국면이나 만남의 타이밍이 바뀌는 흐름입니다.",
      career: "기회, 이동, 일정 변화처럼 상황의 바퀴가 움직일 수 있습니다.",
      money: "변동성이 있으므로 흐름을 읽되 무리한 확신은 피하는 편이 좋습니다.",
      general: "순환과 타이밍을 의식하며 유연하게 대응하라는 카드입니다.",
    },
  },
  {
    id: 11,
    roman: "XI",
    slug: "justice",
    nameEn: "JUSTICE",
    nameKo: "정의",
    image: manyangAssets.tarot.major.justice,
    keywords: ["균형", "판단", "책임", "진실"],
    visualSymbols: ["저울", "검", "왕좌", "기둥"],
    mood: "감정보다 사실과 원인과 결과를 차분히 따져 보는 명료한 분위기입니다.",
    upright: {
      summary: "공정한 판단과 책임 있는 선택이 상황의 균형을 잡는 흐름입니다.",
      dailyFlow: "말과 행동의 결과를 확인하고 기준에 맞춰 정리할 일이 생길 수 있습니다.",
      advice: "감정적 해석보다 사실, 약속, 책임의 범위를 먼저 살피세요.",
    },
    reversed: {
      summary: "불균형한 판단이나 책임 회피가 문제를 흐리게 만들 수 있습니다.",
      dailyFlow: "억울함이나 편견이 커질 수 있으니 자료와 맥락을 다시 확인해야 합니다.",
      advice: "누가 맞는지보다 어떤 기준이 공정한지 차분히 따져 보세요.",
    },
    contexts: {
      love: "관계 안의 약속, 책임, 균형을 점검하는 흐름입니다.",
      career: "계약, 평가, 규정, 의사결정에서 공정성이 중요합니다.",
      money: "수입과 지출, 계약 조건, 책임 범위를 명확히 해야 합니다.",
      general: "원인과 결과를 인정하고 균형 잡힌 결정을 돕는 카드입니다.",
    },
  },
  {
    id: 12,
    roman: "XII",
    slug: "the-hanged-man",
    nameEn: "THE HANGED MAN",
    nameKo: "매달린 사람",
    image: manyangAssets.tarot.major.hangedMan,
    keywords: ["정지", "관점 전환", "수용", "기다림"],
    visualSymbols: ["거꾸로 매달린 인물", "묶인 발", "후광", "나무"],
    mood: "멈춰 있는 듯하지만 시야가 바뀌며 다른 의미가 드러나는 분위기입니다.",
    upright: {
      summary: "억지로 밀기보다 멈춤과 관점 전환이 필요한 흐름입니다.",
      dailyFlow: "진행이 느려져도 그 사이에 다른 해석과 선택지가 보일 수 있습니다.",
      advice: "당장 해결하려는 힘을 내려놓고 상황을 거꾸로 바라보세요.",
    },
    reversed: {
      summary: "의미 없는 희생이나 정체가 길어지며 답답함이 커질 수 있습니다.",
      dailyFlow: "기다림인지 회피인지 구분하지 않으면 에너지가 새어 나가기 쉽습니다.",
      advice: "멈춤의 이유를 묻고 필요 없는 희생은 조용히 거둬들이세요.",
    },
    contexts: {
      love: "관계가 정체되거나 서로를 다른 각도에서 볼 시간이 필요합니다.",
      career: "진행 지연 속에서 방향 재검토와 전략 수정이 중요합니다.",
      money: "결정을 보류하고 조건을 다시 보는 편이 어울립니다.",
      general: "움직임보다 관점의 변화가 먼저라는 카드입니다.",
    },
  },
  {
    id: 13,
    roman: "XIII",
    slug: "death",
    nameEn: "DEATH",
    nameKo: "죽음",
    image: manyangAssets.tarot.major.death,
    keywords: ["끝", "변화", "전환", "해방"],
    visualSymbols: ["해골 기사", "흰 말", "검은 깃발", "떠오르는 태양"],
    mood: "두려움보다 오래된 장의 종료와 다음 단계의 여지를 보여 주는 분위기입니다.",
    upright: {
      summary: "끝나야 할 것을 끝내며 새로운 전환을 맞이하는 흐름입니다.",
      dailyFlow: "붙잡던 습관이나 계획을 정리하면 더 가벼운 선택지가 보일 수 있습니다.",
      advice: "상실로만 보지 말고 비워진 자리에 생길 변화를 살펴보세요.",
    },
    reversed: {
      summary: "끝난 흐름을 붙잡거나 변화를 미루며 피로가 반복될 수 있습니다.",
      dailyFlow: "작은 정리를 미루면 같은 문제를 다시 확인하게 될 수 있습니다.",
      advice: "한 번에 모두 바꾸기보다 놓아야 할 한 가지를 분명히 정하세요.",
    },
    contexts: {
      love: "관계의 낡은 방식이 끝나거나 새로운 형태로 전환될 수 있습니다.",
      career: "역할, 프로젝트, 방향의 종료와 재편을 상징합니다.",
      money: "오래된 지출 습관이나 구조를 정리할 필요가 있습니다.",
      general: "끝은 단절만이 아니라 다음 흐름을 위한 정리라는 카드입니다.",
    },
  },
  {
    id: 14,
    roman: "XIV",
    slug: "temperance",
    nameEn: "TEMPERANCE",
    nameKo: "절제",
    image: manyangAssets.tarot.major.temperance,
    keywords: ["조화", "치유", "균형", "통합"],
    visualSymbols: ["천사", "두 컵", "흐르는 물", "한 발은 물속"],
    mood: "서로 다른 요소를 천천히 섞어 균형을 회복하는 치유의 분위기입니다.",
    upright: {
      summary: "극단보다 조율과 통합을 통해 안정되는 흐름입니다.",
      dailyFlow: "급한 결론보다 속도와 양을 맞추는 조정이 좋은 결과를 돕습니다.",
      advice: "서두르지 말고 서로 다른 필요를 조금씩 섞어 균형점을 찾으세요.",
    },
    reversed: {
      summary: "과하거나 부족한 리듬 때문에 조화가 깨질 수 있습니다.",
      dailyFlow: "일정, 감정, 소비 중 한쪽으로 치우친 부분을 알아차릴 필요가 있습니다.",
      advice: "무리한 절충보다 지금 가장 불균형한 지점을 먼저 조정하세요.",
    },
    contexts: {
      love: "관계 회복과 천천히 맞춰 가는 흐름에 어울립니다.",
      career: "협업, 일정 조율, 프로세스 개선이 중요합니다.",
      money: "수입과 지출의 균형을 회복하고 과한 선택을 줄이는 카드입니다.",
      general: "극단보다 조화로운 통합을 권하는 카드입니다.",
    },
  },
  {
    id: 15,
    roman: "XV",
    slug: "the-devil",
    nameEn: "THE DEVIL",
    nameKo: "악마",
    image: manyangAssets.tarot.major.devil,
    keywords: ["집착", "유혹", "속박", "그림자"],
    visualSymbols: ["묶인 인물", "사슬", "어둠의 제단", "뿔 달린 존재"],
    mood: "강한 끌림과 속박의 감각이 동시에 느껴지는 무거운 분위기입니다.",
    upright: {
      summary: "무엇이 나를 묶고 있는지 직시해야 하는 흐름입니다.",
      dailyFlow: "습관, 욕망, 의존의 패턴이 선명하게 보일 수 있습니다.",
      advice: "탓하기보다 반복되는 끌림과 대가를 정직하게 적어 보세요.",
    },
    reversed: {
      summary: "속박을 알아차리고 조금씩 벗어날 가능성이 생기는 흐름입니다.",
      dailyFlow: "오래된 패턴을 끊고 싶은 마음이 올라오지만 작은 실천이 중요합니다.",
      advice: "한 번의 결심보다 접근 가능한 거리 두기와 도움 요청을 선택하세요.",
    },
    contexts: {
      love: "강한 끌림 속에 의존, 질투, 불균형이 함께 있는지 살펴야 합니다.",
      career: "성과나 권력에 과하게 묶여 있는 구조를 확인하는 흐름입니다.",
      money: "욕망 기반 소비나 반복되는 재정 습관을 점검할 필요가 있습니다.",
      general: "그림자를 외면하지 않고 묶인 지점을 보는 카드입니다.",
    },
  },
  {
    id: 16,
    roman: "XVI",
    slug: "the-tower",
    nameEn: "THE TOWER",
    nameKo: "탑",
    image: manyangAssets.tarot.major.tower,
    keywords: ["붕괴", "충격", "각성", "재건"],
    visualSymbols: ["번개", "무너지는 탑", "떨어지는 인물", "불꽃"],
    mood: "불편하지만 오래된 구조를 다시 보게 만드는 강한 변화의 분위기입니다.",
    upright: {
      summary: "취약한 구조가 드러나며 재점검과 재건이 필요한 흐름입니다.",
      dailyFlow: "예상 밖의 소식이나 깨달음이 계획을 수정하게 만들 수 있습니다.",
      advice: "무너지는 부분을 붙잡기보다 무엇을 새로 세울지 살피세요.",
    },
    reversed: {
      summary: "변화의 신호를 알면서도 미루거나 내부 균열을 감추기 쉽습니다.",
      dailyFlow: "큰 충돌 전에 작은 경고를 알아차리고 조정할 여지가 있습니다.",
      advice: "불편한 사실을 피하지 말고 점검 가능한 부분부터 고쳐 보세요.",
    },
    contexts: {
      love: "관계의 숨은 문제가 드러나며 구조를 다시 봐야 할 수 있습니다.",
      career: "계획 수정, 시스템 문제, 조직 변화의 신호로 읽을 수 있습니다.",
      money: "리스크 노출과 안전장치 점검이 필요한 흐름입니다.",
      general: "붕괴 자체보다 그 뒤의 재건 가능성을 보라는 카드입니다.",
    },
  },
  {
    id: 17,
    roman: "XVII",
    slug: "the-star",
    nameEn: "THE STAR",
    nameKo: "별",
    image: manyangAssets.tarot.major.star,
    keywords: ["희망", "치유", "회복", "영감"],
    visualSymbols: ["큰 별", "물 붓는 인물", "작은 별들", "고요한 물"],
    mood: "어둠 뒤에 맑은 가능성과 회복의 숨이 다시 들어오는 분위기입니다.",
    upright: {
      summary: "희망과 치유가 천천히 회복되며 미래 감각이 맑아지는 흐름입니다.",
      dailyFlow: "큰 성과보다 마음을 다시 열게 하는 작은 신호가 중요할 수 있습니다.",
      advice: "지금 보이는 작은 가능성을 돌보고 회복의 리듬을 믿어 보세요.",
    },
    reversed: {
      summary: "희망을 잃거나 회복이 더디게 느껴져 자기 불신이 커질 수 있습니다.",
      dailyFlow: "밝은 신호를 보아도 쉽게 믿기 어려운 마음이 올라올 수 있습니다.",
      advice: "거창한 확신보다 오늘 회복을 돕는 작은 행동 하나를 선택하세요.",
    },
    contexts: {
      love: "신뢰 회복과 맑은 가능성을 다시 보는 흐름입니다.",
      career: "비전, 영감, 장기 방향을 회복하는 데 도움이 됩니다.",
      money: "즉각적인 확정보다 안정적인 개선 가능성에 초점이 있습니다.",
      general: "상처 이후에도 희망을 다시 돌볼 수 있음을 보여 주는 카드입니다.",
    },
  },
  {
    id: 18,
    roman: "XVIII",
    slug: "the-moon",
    nameEn: "THE MOON",
    nameKo: "달",
    image: manyangAssets.tarot.major.moon,
    keywords: ["불안", "환상", "무의식", "혼란"],
    visualSymbols: ["달", "개와 늑대", "물가의 가재", "안개 낀 길"],
    mood: "분명하지 않은 밤길처럼 직감과 착각이 함께 떠오르는 몽환적인 분위기입니다.",
    upright: {
      summary: "정보가 흐릿하고 감춰진 감정이나 불안이 영향을 주는 흐름입니다.",
      dailyFlow: "확신이 부족한 상태에서는 판단을 미루고 관찰하는 편이 좋습니다.",
      advice: "불안을 사실로 단정하지 말고 확인 가능한 단서를 차분히 모으세요.",
    },
    reversed: {
      summary: "혼란의 원인이 조금씩 드러나거나 자기기만에서 벗어날 여지가 생깁니다.",
      dailyFlow: "막연한 두려움이 이름을 얻으면서 정리될 수 있는 흐름입니다.",
      advice: "감정을 숨기기보다 적어 보고 사실과 상상을 분리해 보세요.",
    },
    contexts: {
      love: "오해, 숨은 감정, 불안정한 신호를 조심스럽게 살펴야 합니다.",
      career: "정보 부족이나 불명확한 계획 속에서 섣부른 판단은 피하는 편이 좋습니다.",
      money: "조건이 흐릿한 거래나 막연한 기대를 세부적으로 확인해야 합니다.",
      general: "밤길을 걷듯 천천히 감정과 사실을 구분하라는 카드입니다.",
    },
  },
  {
    id: 19,
    roman: "XIX",
    slug: "the-sun",
    nameEn: "THE SUN",
    nameKo: "해",
    image: manyangAssets.tarot.major.sun,
    keywords: ["명확함", "생명력", "기쁨", "성취"],
    visualSymbols: ["밝은 태양", "아이", "흰 말", "해바라기"],
    mood: "숨겨진 것이 밝게 드러나고 생명력이 회복되는 환한 분위기입니다.",
    upright: {
      summary: "명확함과 활력이 돌아오며 긍정적인 표현이 쉬워지는 흐름입니다.",
      dailyFlow: "솔직하게 드러내고 함께 나눌수록 일이 밝아질 수 있습니다.",
      advice: "기쁨을 축소하지 말고 가능한 만큼 밝게 표현해 보세요.",
    },
    reversed: {
      summary: "기쁨이 지연되거나 자신감이 완전히 올라오지 못할 수 있습니다.",
      dailyFlow: "좋은 신호가 있어도 피로감 때문에 온전히 받아들이기 어려울 수 있습니다.",
      advice: "완벽한 확신을 기다리기보다 작은 성취를 인정하는 연습을 하세요.",
    },
    contexts: {
      love: "솔직함과 따뜻한 표현이 관계를 밝게 만드는 흐름입니다.",
      career: "성과, 인정, 공개적인 결과와 연결될 수 있습니다.",
      money: "긍정적인 개선 가능성이 보이지만 세부 확인은 계속 필요합니다.",
      general: "명확함과 생명력으로 현재를 환하게 비추는 카드입니다.",
    },
  },
  {
    id: 20,
    roman: "XX",
    slug: "judgement",
    nameEn: "JUDGEMENT",
    nameKo: "심판",
    image: manyangAssets.tarot.major.judgement,
    keywords: ["각성", "부름", "재평가", "새로운 단계"],
    visualSymbols: ["나팔 부는 천사", "깨어나는 사람들", "빛", "관"],
    mood: "지나온 시간을 돌아보고 더 큰 부름에 응답하려는 각성의 분위기입니다.",
    upright: {
      summary: "과거를 재평가하고 새로운 단계로 응답할 준비가 되는 흐름입니다.",
      dailyFlow: "미뤄 둔 결정이나 정리해야 할 일이 다시 의미 있게 떠오를 수 있습니다.",
      advice: "자책보다 배움을 정리하고 지금의 부름에 응답해 보세요.",
    },
    reversed: {
      summary: "결정을 미루거나 자기비판에 묶여 다음 단계로 나아가기 어려울 수 있습니다.",
      dailyFlow: "예전 선택을 반복해서 떠올리며 현재의 응답을 늦출 수 있습니다.",
      advice: "과거를 판결문처럼 붙잡지 말고 배운 점과 다음 행동을 분리하세요.",
    },
    contexts: {
      love: "관계의 과거를 다시 보고 새롭게 응답할 지점을 묻는 흐름입니다.",
      career: "평가, 전환, 소명감, 재도전의 신호로 읽을 수 있습니다.",
      money: "지난 재정 선택을 정리하고 새로운 기준을 세우는 데 어울립니다.",
      general: "과거를 정리하고 더 성숙한 응답을 선택하라는 카드입니다.",
    },
  },
  {
    id: 21,
    roman: "XXI",
    slug: "the-world",
    nameEn: "THE WORLD",
    nameKo: "세계",
    image: manyangAssets.tarot.major.world,
    keywords: ["완성", "통합", "성취", "조화"],
    visualSymbols: ["월계관", "춤추는 인물", "네 상징 존재", "완성의 고리"],
    mood: "긴 여정이 하나의 고리로 완성되고 다음 순환이 보이는 조화로운 분위기입니다.",
    upright: {
      summary: "한 주기나 과제가 통합되며 완성의 감각을 얻는 흐름입니다.",
      dailyFlow: "마무리와 정리가 잘 맞아떨어지고 다음 단계의 윤곽이 보일 수 있습니다.",
      advice: "완성한 것을 인정하고 배운 내용을 다음 순환의 기반으로 삼으세요.",
    },
    reversed: {
      summary: "마지막 정리나 인정이 늦어져 완성감이 흐려질 수 있습니다.",
      dailyFlow: "거의 끝난 일을 마무리하지 못해 에너지가 흩어질 수 있습니다.",
      advice: "완벽을 기다리기보다 닫아야 할 고리를 하나씩 정리하세요.",
    },
    contexts: {
      love: "관계가 한 단계 안정되거나 중요한 주기를 마무리하는 흐름입니다.",
      career: "프로젝트 완료, 성취, 확장 가능성을 상징합니다.",
      money: "재정 목표의 마무리나 전체 구조 점검에 어울립니다.",
      general: "완성과 통합을 인정하고 다음 여정으로 넘어가라는 카드입니다.",
    },
  },
] as const satisfies readonly TarotMajorCard[];

export function getTarotMajorCardById(id: number): TarotMajorCard | null {
  return tarotMajorCards.find((card) => card.id === id) ?? null;
}
